<?php

declare(strict_types=1);

namespace Upmind\DomainNameApiSdk\SDK;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'CheckAvailability' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailability',
            'CheckAvailabilityResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailabilityResponse',
            'CheckBulkAvailability' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckBulkAvailability',
            'CheckBulkAvailabilityResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckBulkAvailabilityResponse',
            'CheckAvailabilityIdn' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailabilityIdn',
            'CheckAvailabilityIdnResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailabilityIdnResponse',
            'Register' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Register',
            'RegisterResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RegisterResponse',
            'RegisterWithContactInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RegisterWithContactInfo',
            'RegisterWithContactInfoResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RegisterWithContactInfoResponse',
            'ModifyNameServer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyNameServer',
            'ModifyNameServerResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyNameServerResponse',
            'ModifyContacts' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyContacts',
            'ModifyContactsResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyContactsResponse',
            'GetContacts' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetContacts',
            'GetContactsResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetContactsResponse',
            'SaveContacts' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SaveContacts',
            'SaveContactsResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SaveContactsResponse',
            'ModifyAuthCode' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAuthCode',
            'ModifyAuthCodeResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAuthCodeResponse',
            'ModifyStatus' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyStatus',
            'ModifyStatusResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyStatusResponse',
            'EnableTheftProtectionLock' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\EnableTheftProtectionLock',
            'EnableTheftProtectionLockResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\EnableTheftProtectionLockResponse',
            'DisableTheftProtectionLock' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DisableTheftProtectionLock',
            'DisableTheftProtectionLockResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DisableTheftProtectionLockResponse',
            'ModifyPrivacyProtectionStatus' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyPrivacyProtectionStatus',
            'ModifyPrivacyProtectionStatusResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyPrivacyProtectionStatusResponse',
            'AddChildNameServer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\AddChildNameServer',
            'AddChildNameServerResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\AddChildNameServerResponse',
            'ModifyChildNameServer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyChildNameServer',
            'ModifyChildNameServerResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyChildNameServerResponse',
            'DeleteChildNameServer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteChildNameServer',
            'DeleteChildNameServerResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteChildNameServerResponse',
            'GetChildNameServer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServer',
            'GetChildNameServerResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServerResponse',
            'GetChildNameServers' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServers',
            'GetChildNameServersResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServersResponse',
            'Delete' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Delete',
            'DeleteResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteResponse',
            'Renew' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Renew',
            'RenewResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RenewResponse',
            'GetDetails' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetails',
            'GetDetailsResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetailsResponse',
            'GetList' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetList',
            'GetListResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetListResponse',
            'CheckTransfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckTransfer',
            'CheckTransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckTransferResponse',
            'Transfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Transfer',
            'TransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\TransferResponse',
            'QueryTransfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\QueryTransfer',
            'QueryTransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\QueryTransferResponse',
            'ApproveTransfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ApproveTransfer',
            'ApproveTransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ApproveTransferResponse',
            'RejectTransfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RejectTransfer',
            'RejectTransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RejectTransferResponse',
            'CancelTransfer' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CancelTransfer',
            'CancelTransferResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CancelTransferResponse',
            'Restore' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Restore',
            'RestoreResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RestoreResponse',
            'PreRegistiration' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PreRegistiration',
            'PreRegistirationResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PreRegistirationResponse',
            'ResendIncomingTransferFOAMail' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendIncomingTransferFOAMail',
            'ResendIncomingTransferFOAMailResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendIncomingTransferFOAMailResponse',
            'ResendOutgoingTransferFOAMail' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendOutgoingTransferFOAMail',
            'ResendOutgoingTransferFOAMailResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendOutgoingTransferFOAMailResponse',
            'Push' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Push',
            'PushResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PushResponse',
            'Sync' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\Sync',
            'SyncResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SyncResponse',
            'SetRenewalMode' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SetRenewalMode',
            'SetRenewalModeResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SetRenewalModeResponse',
            'PayRenewal' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PayRenewal',
            'PayRenewalResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PayRenewalResponse',
            'ModifyAdditionalAttributes' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAdditionalAttributes',
            'ModifyAdditionalAttributesResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAdditionalAttributesResponse',
            'DENIC_CreateAuthInfo1' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo1',
            'DENIC_CreateAuthInfo1Response' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo1Response',
            'DENIC_CreateAuthInfo2' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo2',
            'DENIC_CreateAuthInfo2Response' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo2Response',
            'DENIC_DeleteAuthInfo1' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_DeleteAuthInfo1',
            'DENIC_DeleteAuthInfo1Response' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_DeleteAuthInfo1Response',
            'GetTldList' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetTldList',
            'GetTldListResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetTldListResponse',
            'SyncFromRegistry' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SyncFromRegistry',
            'SyncFromRegistryResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SyncFromRegistryResponse',
            'GetDetailsFromRegistry' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetailsFromRegistry',
            'GetDetailsFromRegistryResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetailsFromRegistryResponse',
            'GetForward' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetForward',
            'GetForwardResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetForwardResponse',
            'CreateForward' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CreateForward',
            'CreateForwardResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CreateForwardResponse',
            'ModifyForward' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyForward',
            'ModifyForwardResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyForwardResponse',
            'DeleteForward' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteForward',
            'DeleteForwardResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteForwardResponse',
            'GetCurrentBalance' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetCurrentBalance',
            'GetCurrentBalanceResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetCurrentBalanceResponse',
            'ModifyRenewalMode' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyRenewalMode',
            'ModifyRenewalModeResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyRenewalModeResponse',
            'CheckAvailabilityRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailabilityRequest',
            'CheckAvailabilityIdnRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckAvailabilityIdnRequest',
            'RegisterRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RegisterRequest',
            'RegisterWithContactInfoRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RegisterWithContactInfoRequest',
            'ModifyNameServerRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyNameServerRequest',
            'ModifyContactsRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyContactsRequest',
            'GetContactsRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetContactsRequest',
            'SaveContactsRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SaveContactsRequest',
            'ModifyAuthCodeRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAuthCodeRequest',
            'ModifyStatusRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyStatusRequest',
            'EnableTheftProtectionLockRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\EnableTheftProtectionLockRequest',
            'DisableTheftProtectionLockRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DisableTheftProtectionLockRequest',
            'ModifyPrivacyProtectionStatusRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyPrivacyProtectionStatusRequest',
            'AddChildNameServerRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\AddChildNameServerRequest',
            'ModifyChildNameServerRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyChildNameServerRequest',
            'DeleteChildNameServerRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteChildNameServerRequest',
            'GetChildNameServerRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServerRequest',
            'GetChildNameServersRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetChildNameServersRequest',
            'DeleteRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DeleteRequest',
            'RenewRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RenewRequest',
            'GetDetailsRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetailsRequest',
            'GetListRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetListRequest',
            'CheckTransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CheckTransferRequest',
            'TransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\TransferRequest',
            'QueryTransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\QueryTransferRequest',
            'ApproveTransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ApproveTransferRequest',
            'RejectTransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RejectTransferRequest',
            'CancelTransferRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CancelTransferRequest',
            'RestoreRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RestoreRequest',
            'ResendIncomingTransferFOAMailRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendIncomingTransferFOAMailRequest',
            'ResendOutgoingTransferFOAMailRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ResendOutgoingTransferFOAMailRequest',
            'PushRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PushRequest',
            'SyncRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SyncRequest',
            'SetRenewalModeRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SetRenewalModeRequest',
            'PayRenewalRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PayRenewalRequest',
            'ModifyAdditionalAttributesRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyAdditionalAttributesRequest',
            'DENIC_CreateAuthInfo1Request' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo1Request',
            'DENIC_CreateAuthInfo2Request' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_CreateAuthInfo2Request',
            'DENIC_DeleteAuthInfo1Request' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DENIC_DeleteAuthInfo1Request',
            'GetTldListRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetTldListRequest',
            'SyncFromRegistryRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\SyncFromRegistryRequest',
            'GetDetailsFromRegistryRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetDetailsFromRegistryRequest',
            'ForwardRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ForwardRequest',
            'ForwardResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ForwardResponse',
            'ModifyRenewealModeRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ModifyRenewealModeRequest',
            'BaseMethodRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\BaseMethodRequest',
            'BaseMethodResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\BaseMethodResponse',
            'ArrayOfRGPStatus' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfRGPStatus',
            'RGPStatus' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\RGPStatus',
            'BasePagedMethodRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\BasePagedMethodRequest',
            'BasePagedMethodResponse' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\BasePagedMethodResponse',
            'PreRegistirationRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\PreRegistirationRequest',
            'ArrayOfstring' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfstring',
            'ArrayOfKeyValueOfstringstring' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfKeyValueOfstringstring',
            'KeyValueOfstringstring' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\KeyValueOfstringstring',
            'ArrayOfDomainAvailabilityInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfDomainAvailabilityInfo',
            'DomainAvailabilityInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DomainAvailabilityInfo',
            'DomainInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\DomainInfo',
            'ArrayOfChildNameServerInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfChildNameServerInfo',
            'ChildNameServerInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ChildNameServerInfo',
            'ContactInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\ContactInfo',
            'ArrayOfDomainInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfDomainInfo',
            'ArrayOfTldInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfTldInfo',
            'TldInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\TldInfo',
            'ArrayOfTldPriceInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\ArrayType\\ArrayOfTldPriceInfo',
            'TldPriceInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\TldPriceInfo',
            'CurrencyWithExchangeInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CurrencyWithExchangeInfo',
            'CurrencyInfo' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\CurrencyInfo',
            'BaseData' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\BaseData',
            'GetCurrentBalanceRequest' => '\\Upmind\\DomainNameApiSdk\\SDK\\StructType\\GetCurrentBalanceRequest',
        ];
    }
}
